# ----------------------------------------------------------------------------
# Name     : .bashrc
# Function : user startup-file for bash
# Origin   : created by /env/common/bin/login_files_change
#
# Note     : Please do not edit this file until you have read the
#            site policy file for dot-files: /etc/home/README
#
# ----------------------------------------------------------------------------
if [ -r /etc/home/bashrc -a -d /env ]; then
 # MWP: use ARC environment
 . /etc/home/bashrc
elif [ -r $HOME/.bashrc.old ]; then
 # fall back to legacy environment
 . $HOME/.bashrc.old
fi
#
