#!/usr/bin/env csh

# setup file to store bookmarks
if ( ! "$?SDIRS" ) setenv SDIRS ~/.cdirs
touch $SDIRS

# cshmarks alias
alias l     'source ~/.cshmarks/list'
alias s     'source ~/.cshmarks/save'
alias g     'source ~/.cshmarks/goto'
alias d     'source ~/.cshmarks/delete'

# completion command
complete g 'p/1/`cat $SDIRS | cut -d" " -f1`/'
complete d 'p/1/`cat $SDIRS | cut -d" " -f1`/'
