#!/usr/bin/env csh

if ( "X$1" == "X" ) then
  echo "\033[0;31mbookmark name required\033[0m"
  exit
else
  if ( "$1" != `echo $1 | sed 's/[^A-Za-z0-9_]//g'` ) then
    echo "\033[0;31mbookmark name is not valid\033[0m"
    exit
  else
    # Delete previous bookmark with same name
    # safely create a temp file
    set t = `mktemp -t bashmarks.XXXXXX || exit 1`

    # purge line
    sed "/^$1 /d" "$SDIRS" > "$t"
    \mv "$t" "$SDIRS"

    # cleanup temp file
    \rm -f -- "$t"
    
    # Save the new bookmark
    echo "$1 $cwd" >> $SDIRS
    echo "\033[0;32mbookmark $1 saved\033[0m"
  endif
endif
